language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch
  - mysql

before_install:
  - pip install flake8
  - pip install coveralls
  - pip install kingarthur
  - pip install perceval
  - pip install perceval-mozilla
  - pip install perceval-opnfv
  - pip install pandas==0.18.1
  - pip install redis
  - pip install sortinghat
  - pip install PyMySQL
  - pip install httpretty==0.8.6
  - pip install cereslib
  - pip install elasticsearch==5.5.1
  - pip install elasticsearch-dsl==5.3.0
  - pip install grimoirelab-toolkit

# install:
#   - ./setup.py install

before_script:
  - sleep 15

script:
  - flake8 .
  - mysqladmin -u root create test_sh
  - mysqladmin -u root create test_projects
  - mysql -u root test_projects < tests/test_projects.sql
  - cd tests && ./run_tests.py
